// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sim

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// P4PCoordianteClient is the client API for P4PCoordiante service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type P4PCoordianteClient interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error)
	// A server-to-client streaming RPC.
	//
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (P4PCoordiante_ListFeaturesClient, error)
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	RecordRoute(ctx context.Context, opts ...grpc.CallOption) (P4PCoordiante_RecordRouteClient, error)
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	RouteChat(ctx context.Context, opts ...grpc.CallOption) (P4PCoordiante_RouteChatClient, error)
}

type p4PCoordianteClient struct {
	cc grpc.ClientConnInterface
}

func NewP4PCoordianteClient(cc grpc.ClientConnInterface) P4PCoordianteClient {
	return &p4PCoordianteClient{cc}
}

func (c *p4PCoordianteClient) GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error) {
	out := new(Feature)
	err := c.cc.Invoke(ctx, "/p4p.p4p.sim.P4PCoordiante/GetFeature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p4PCoordianteClient) ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (P4PCoordiante_ListFeaturesClient, error) {
	stream, err := c.cc.NewStream(ctx, &P4PCoordiante_ServiceDesc.Streams[0], "/p4p.p4p.sim.P4PCoordiante/ListFeatures", opts...)
	if err != nil {
		return nil, err
	}
	x := &p4PCoordianteListFeaturesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type P4PCoordiante_ListFeaturesClient interface {
	Recv() (*Feature, error)
	grpc.ClientStream
}

type p4PCoordianteListFeaturesClient struct {
	grpc.ClientStream
}

func (x *p4PCoordianteListFeaturesClient) Recv() (*Feature, error) {
	m := new(Feature)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *p4PCoordianteClient) RecordRoute(ctx context.Context, opts ...grpc.CallOption) (P4PCoordiante_RecordRouteClient, error) {
	stream, err := c.cc.NewStream(ctx, &P4PCoordiante_ServiceDesc.Streams[1], "/p4p.p4p.sim.P4PCoordiante/RecordRoute", opts...)
	if err != nil {
		return nil, err
	}
	x := &p4PCoordianteRecordRouteClient{stream}
	return x, nil
}

type P4PCoordiante_RecordRouteClient interface {
	Send(*Point) error
	CloseAndRecv() (*RouteSummary, error)
	grpc.ClientStream
}

type p4PCoordianteRecordRouteClient struct {
	grpc.ClientStream
}

func (x *p4PCoordianteRecordRouteClient) Send(m *Point) error {
	return x.ClientStream.SendMsg(m)
}

func (x *p4PCoordianteRecordRouteClient) CloseAndRecv() (*RouteSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RouteSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *p4PCoordianteClient) RouteChat(ctx context.Context, opts ...grpc.CallOption) (P4PCoordiante_RouteChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &P4PCoordiante_ServiceDesc.Streams[2], "/p4p.p4p.sim.P4PCoordiante/RouteChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &p4PCoordianteRouteChatClient{stream}
	return x, nil
}

type P4PCoordiante_RouteChatClient interface {
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc.ClientStream
}

type p4PCoordianteRouteChatClient struct {
	grpc.ClientStream
}

func (x *p4PCoordianteRouteChatClient) Send(m *RouteNote) error {
	return x.ClientStream.SendMsg(m)
}

func (x *p4PCoordianteRouteChatClient) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// P4PCoordianteServer is the server API for P4PCoordiante service.
// All implementations must embed UnimplementedP4PCoordianteServer
// for forward compatibility
type P4PCoordianteServer interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetFeature(context.Context, *Point) (*Feature, error)
	// A server-to-client streaming RPC.
	//
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	ListFeatures(*Rectangle, P4PCoordiante_ListFeaturesServer) error
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	RecordRoute(P4PCoordiante_RecordRouteServer) error
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	RouteChat(P4PCoordiante_RouteChatServer) error
	mustEmbedUnimplementedP4PCoordianteServer()
}

// UnimplementedP4PCoordianteServer must be embedded to have forward compatible implementations.
type UnimplementedP4PCoordianteServer struct {
}

func (UnimplementedP4PCoordianteServer) GetFeature(context.Context, *Point) (*Feature, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeature not implemented")
}
func (UnimplementedP4PCoordianteServer) ListFeatures(*Rectangle, P4PCoordiante_ListFeaturesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListFeatures not implemented")
}
func (UnimplementedP4PCoordianteServer) RecordRoute(P4PCoordiante_RecordRouteServer) error {
	return status.Errorf(codes.Unimplemented, "method RecordRoute not implemented")
}
func (UnimplementedP4PCoordianteServer) RouteChat(P4PCoordiante_RouteChatServer) error {
	return status.Errorf(codes.Unimplemented, "method RouteChat not implemented")
}
func (UnimplementedP4PCoordianteServer) mustEmbedUnimplementedP4PCoordianteServer() {}

// UnsafeP4PCoordianteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to P4PCoordianteServer will
// result in compilation errors.
type UnsafeP4PCoordianteServer interface {
	mustEmbedUnimplementedP4PCoordianteServer()
}

func RegisterP4PCoordianteServer(s grpc.ServiceRegistrar, srv P4PCoordianteServer) {
	s.RegisterService(&P4PCoordiante_ServiceDesc, srv)
}

func _P4PCoordiante_GetFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Point)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P4PCoordianteServer).GetFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p4p.p4p.sim.P4PCoordiante/GetFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P4PCoordianteServer).GetFeature(ctx, req.(*Point))
	}
	return interceptor(ctx, in, info, handler)
}

func _P4PCoordiante_ListFeatures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Rectangle)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(P4PCoordianteServer).ListFeatures(m, &p4PCoordianteListFeaturesServer{stream})
}

type P4PCoordiante_ListFeaturesServer interface {
	Send(*Feature) error
	grpc.ServerStream
}

type p4PCoordianteListFeaturesServer struct {
	grpc.ServerStream
}

func (x *p4PCoordianteListFeaturesServer) Send(m *Feature) error {
	return x.ServerStream.SendMsg(m)
}

func _P4PCoordiante_RecordRoute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(P4PCoordianteServer).RecordRoute(&p4PCoordianteRecordRouteServer{stream})
}

type P4PCoordiante_RecordRouteServer interface {
	SendAndClose(*RouteSummary) error
	Recv() (*Point, error)
	grpc.ServerStream
}

type p4PCoordianteRecordRouteServer struct {
	grpc.ServerStream
}

func (x *p4PCoordianteRecordRouteServer) SendAndClose(m *RouteSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *p4PCoordianteRecordRouteServer) Recv() (*Point, error) {
	m := new(Point)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _P4PCoordiante_RouteChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(P4PCoordianteServer).RouteChat(&p4PCoordianteRouteChatServer{stream})
}

type P4PCoordiante_RouteChatServer interface {
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc.ServerStream
}

type p4PCoordianteRouteChatServer struct {
	grpc.ServerStream
}

func (x *p4PCoordianteRouteChatServer) Send(m *RouteNote) error {
	return x.ServerStream.SendMsg(m)
}

func (x *p4PCoordianteRouteChatServer) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// P4PCoordiante_ServiceDesc is the grpc.ServiceDesc for P4PCoordiante service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var P4PCoordiante_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p4p.p4p.sim.P4PCoordiante",
	HandlerType: (*P4PCoordianteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeature",
			Handler:    _P4PCoordiante_GetFeature_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListFeatures",
			Handler:       _P4PCoordiante_ListFeatures_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RecordRoute",
			Handler:       _P4PCoordiante_RecordRoute_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RouteChat",
			Handler:       _P4PCoordiante_RouteChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "p4p/p4p/sim/p4p/p4p.proto",
}
