// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package p4p

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserSClient is the client API for UserS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserSClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersReply, error)
}

type userSClient struct {
	cc grpc.ClientConnInterface
}

func NewUserSClient(cc grpc.ClientConnInterface) UserSClient {
	return &userSClient{cc}
}

func (c *userSClient) SayHello(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersReply, error) {
	out := new(UsersReply)
	err := c.cc.Invoke(ctx, "/p4p.p4p.user.p4p.UserS/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSServer is the server API for UserS service.
// All implementations must embed UnimplementedUserSServer
// for forward compatibility
type UserSServer interface {
	// Sends a greeting
	SayHello(context.Context, *UsersRequest) (*UsersReply, error)
	mustEmbedUnimplementedUserSServer()
}

// UnimplementedUserSServer must be embedded to have forward compatible implementations.
type UnimplementedUserSServer struct {
}

func (UnimplementedUserSServer) SayHello(context.Context, *UsersRequest) (*UsersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedUserSServer) mustEmbedUnimplementedUserSServer() {}

// UnsafeUserSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserSServer will
// result in compilation errors.
type UnsafeUserSServer interface {
	mustEmbedUnimplementedUserSServer()
}

func RegisterUserSServer(s grpc.ServiceRegistrar, srv UserSServer) {
	s.RegisterService(&UserS_ServiceDesc, srv)
}

func _UserS_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p4p.p4p.user.p4p.UserS/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSServer).SayHello(ctx, req.(*UsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserS_ServiceDesc is the grpc.ServiceDesc for UserS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p4p.p4p.user.p4p.UserS",
	HandlerType: (*UserSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _UserS_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "p4p/p4p/user/p4p/users.proto",
}
